#!/usr/bin/env node
require('shelljs/global');
const program = require('commander');
const currentPath = __dirname;

program
    .version(require('./package.json').version);

program
.command('say-somethings')
.alias('say')
.arguments('<words> <timer>')
.description('Say somethings how many times you want')
.action(function (words,timer) {
    console.log(words,timer)
    if(words===undefined)words = 'error';
    if(timer===undefined)timer = 1;

    exec('bash ' + currentPath + '/src/trol.sh ' + words + ' '+timer);
});

program.parse(process.argv);

if (!program.args.length)
    program.help();